---
driver:
  name: vagrant
  customize:
    cableconnected1: 'on'

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2
    driver_config:
        network:
            - ["forwarded_port", {guest: 3141, host: 3141}]
            - ["forwarded_port", {guest: 8080, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[devpiserver::default]
      - recipe[devpiserver::supervisord]
      - recipe[devpiserver::nginx]
    attributes:
